### ISSUE TITLE
vcmsa Error when executing

### ISSUE THREAD

**Issue by gmartinezredondo** [clairemcwhite/vcmsa#10]
Hello!

I am trying to use vcmsa on a group of 7 proteins but I get the following error:

```
Traceback (most recent call last):
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not StringIO

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/metazomics/miniconda3/envs/vcmsa_env/bin/vcmsa", line 4, in <module>
    __import__('pkg_resources').run_script('vcmsa==0.1.0', 'vcmsa')
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/vcmsa-0.1.0-py3.9.egg/EGG-INFO/scripts/vcmsa", line 740, in <module>
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/vcmsa-0.1.0-py3.9.egg/EGG-INFO/scripts/vcmsa", line 573, in do_msa
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/vcmsa-0.1.0-py3.9.egg/vcmsa/vcmsa_utils.py", line 113, in format_aln
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/Bio/Align/__init__.py", line 354, in __format__
    AlignIO.write([self], handle, format_spec)
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/Bio/AlignIO/__init__.py", line 214, in write
    count = writer_class(fp).write_file(alignments)
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/Bio/AlignIO/Interfaces.py", line 129, in write_file
    self.write_alignment(alignment)
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/Bio/AlignIO/ClustalIO.py", line 28, in write_alignment
    raise ValueError("Non-empty sequences are required")
ValueError: Non-empty sequences are required
Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fd5453d6d30>
Traceback (most recent call last):
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/weakref.py", line 370, in remove
  File "/home/metazomics/miniconda3/envs/vcmsa_env/lib/python3.9/site-packages/vcmsa-0.1.0-py3.9.egg/EGG-INFO/scripts/vcmsa", line 581, in tracefunc
AttributeError: 'NoneType' object has no attribute 'split'
```

Any clue on what may be happening here? I created the conda environment and installed vcmsa from source. Thanks in advance!

**Comment by zolotarovgl** [comment]
I have the same problem and couldn't solve it.

**Comment by clairemcwhite** [comment]
Does the example in the README for you? Could you all let me know the command you used, and the first few entries of the input fasta file? 

Thanks

**Comment by zolotarovgl** [comment]
Sure, the code and the error can be found below:
```
fasta=example_files/LDLa.vie.20seqs.fasta
layers='-16 -15 -14 -13 -12 -11 -10 -9 -8 -7 -6 -5 -4 -3 -2 -1'
model=prot_t5_xl_uniref50
suffix=.16layer.t5.aln
vcmsa  -i $fasta -o $fasta.$suffix --layers  $layers  -m $model --exclude --pca_plot
3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0]
args Namespace(batch_correct=False, cpu_only=False, emb_outfile=None, embed_only=False, embedding_path=None, exclude=True, fasta_path='example_files/LDLa.vie.20seqs.fasta', fully_exclude=False, headnorm=False, heads=None, layers=[-16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1], max_iterations=100, model_name='prot_t5_xl_uniref50', out_path='example_files/LDLa.vie.20seqs.fasta..16layer.t5.aln', padding=0, pca_plot=True, seqlimit=None, seqsimthresh=0.7)
Params Namespace(batch_correct=False, cpu_only=False, emb_outfile=None, embed_only=False, embedding_path=None, exclude=True, fasta_path='example_files/LDLa.vie.20seqs.fasta', fully_exclude=False, headnorm=False, heads=None, layers=[-16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1], max_iterations=100, model_name='prot_t5_xl_uniref50', out_path='example_files/LDLa.vie.20seqs.fasta..16layer.t5.aln', outfile_name='LDLa.vie.20seqs.fasta..16layer.t5', padding=0, pca_plot=True, record_dir='example_files/alignment_files_LDLa.vie.20seqs.fasta..16layer.t5', seqlimit=None, seqsimthresh=0.7)
ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in a REPL (e.g. from the command line), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?
CUDA available? True
Traceback (most recent call last):
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/prot_t5_xl_uniref50/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6421c842-3769b49d415a581b654bb41a)

Repository Not Found for url: https://huggingface.co/prot_t5_xl_uniref50/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/bin/vcmsa", line 4, in <module>
    __import__('pkg_resources').run_script('vcmsa==0.1.0', 'vcmsa')
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1570, in run_script
    exec(script_code, namespace, namespace)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/vcmsa-0.1.0-py3.8.egg/EGG-INFO/scripts/vcmsa", line 675, in <module>
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/vcmsa-0.1.0-py3.8.egg/vcmsa/vcmsa_embed.py", line 383, in get_embeddings
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/vcmsa-0.1.0-py3.8.egg/vcmsa/vcmsa_embed.py", line 309, in load_model
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 896, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: prot_t5_xl_uniref50 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fe6436c1430>
Traceback (most recent call last):
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/weakref.py", line 345, in remove
  File "/home/grygoriyzolotarov/mambaforge/envs/vcmsa_env/lib/python3.8/site-packages/vcmsa-0.1.0-py3.8.egg/EGG-INFO/scripts/vcmsa", line 581, in tracefunc
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by clairemcwhite** [comment]
It looks like the huggingface language model isn't being found. You'll either have to download the model from huggingface (mine is locally named  prot_t5_xl_uniref50) or use name of the repository on huggingface Rostlab/prot_t5_xl_uniref50

**Comment by lukaszsobala** [comment]
The error at the end (in "line 581") is the same error as I was getting in #4. I specified the model in command line (`-m`) but it was still happening.
